### ISSUE TITLE
No way to return to main page

### ISSUE THREAD

**Issue by dougmantis** [scoskey/m301#1]
The main page ("Welcome to the course web site...") Has easily accessed links that allow students to go to sub-pages for notes, homework and the syllabus. However, there's no way to return to the main page from those sub-pages, except by altering the address bar or accessing their search history.
Possible solutions:
- Adding a hyperlink onto the website title ("Math 301, Spring 2020") that leads back to https://scoskey.org/m301/
- Adding a link in the footnotes (near the "Hosted on GitHub Pages") saying something like "return to main page"
- Putting all information in main page (links to syllabus, assignments and homework) in the header of the page, near "Math 301 course resources", so students have no reason to return to the main page (because all the links on the main page are provided)

**Comment by scoskey** [comment]
I noticed that! I was very surprised the theme doesn't have the title link back. I'll either change the theme or add a manual backlink presently. T/Y!!

**Comment by scoskey** [comment]
Fixed by linking the title (046221f7a57227c2218399662b54bf64cb0ab133)
